web/moons/server/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

web/moons/server/moons/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("core.urls")),
    path('queries/', include("queries.urls")),
    path('oidc/', include('mozilla_django_oidc.urls')),
]

web/moons/server/queries/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "queries"

urlpatterns = [
    path('', views.QueryCreateView.as_view(), name='query-create'),
    path('schema', views.DatabaseSchemaView.as_view(), name='schema-view'),
    path('schema/table/<table_name>', views.TableSchemaView.as_view(), name='table-view'),
    path('schema/view/<view_name>', views.ViewSchemaView.as_view(), name='view-view'),
    path('query', views.QueryListView.as_view(), name='query-list'),
    path('query/<int:pk>', views.QueryDetailView.as_view(), name='query-detail'),
    path('query/result/<int:pk>', views.QueryResultView.as_view(), name='query-result'),
    path('query/status/<int:pk>', views.QueryStatusView.as_view(), name='query-status'),
    path('query/an', views.AnonymousQueryCreateView.as_view(), name='anonymous-query-create'),
    path('query/an/<slug>', views.AnonymousQueryDetailView.as_view(), name='anonymous-query-detail'),
    path('query/an/result/<slug>', views.AnonymousQueryResultView.as_view(), name='anonymous-query-result'),
    path('query/an/status/<slug>', views.AnonymousQueryStatusView.as_view(), name='anonymous-query-status'),
]

web/moons/server/queries/models.py
import os
import uuid

from django.conf import settings
from django.db import models

def results_path():
    return os.path.join(settings.LOCAL_FILE_DIR, "results")

class ExecuteSQL(models.Model):

    StatusType = models.TextChoices("StatusType", "CREATED RUNNING COMPLETED")

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    query = models.TextField(blank=True, null=True)
    timeout = models.PositiveSmallIntegerField(null=True, blank=True)
    format = models.CharField(max_length=127, null=True, blank=True)
    status = models.CharField(max_length=127, choices=StatusType.choices, default=StatusType.CREATED)
    created = models.DateTimeField(auto_now_add=True)
    started = models.DateTimeField(null=True, blank=True)
    completed = models.DateTimeField(null=True, blank=True)
    results_file = models.CharField(max_length=1023, blank=True, null=True)
    results_error = models.TextField(blank=True, null=True)

    @property
    def current_status(self):
        if self.status == ExecuteSQL.StatusType.COMPLETED:
            if self.results_error:
                return 'Error'
            else:
                return 'Success'
        elif self.status == ExecuteSQL.StatusType.CREATED:
            return 'Queued'
        return self.get_status_display()

class AnonymousQuery(models.Model):
    sqlquery = models.ForeignKey(ExecuteSQL, on_delete=models.CASCADE)
    slug = models.UUIDField(unique=True, default=uuid.uuid4)

web/moons/server/queries/forms.py
from django import forms
from django.forms.widgets import HiddenInput

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import ExecuteSQL

class SQLQueryForm(forms.ModelForm):

    class Meta:
        model = ExecuteSQL
        fields = ('query', 'timeout', 'format', )
        labels = {
            'timeout': 'Timeout (seconds)'
        }
        help_texts = {
            'timeout': 'Your query will be halted after this time (max 10800)',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['query'] = forms.Field(widget=HiddenInput())
        choices=(
            ('html', 'HTML table summary (results are not saved to a file)'),
            # ('fits', 'FITS FILE (downloadable with HTML table summary on-screen)'),
            # ('votable', 'VOTable FILE (downloadable with HTML table summary on-screen)'),
        )

        self.fields['timeout'].initial = 3600
        self.fields['format'] = forms.ChoiceField(
            choices=choices,
            required=True,
            help_text='The number of rows written to the downloadable files is subject to an upper limit',
        )

        self.helper = FormHelper()
        self.helper.form_tag = False

web/moons/server/queries/views.py
import json

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.urls import reverse
from django.utils.text import slugify
from django.views.generic import TemplateView, CreateView, DetailView, ListView, View
from django.views.generic.detail import SingleObjectMixin
from django_tables2.views import SingleTableMixin

from .models import ExecuteSQL, AnonymousQuery
from .forms import SQLQueryForm
from .tasks import execute, read_table, to_json
from .tables import QueryTable

import logging
logger = logging.getLogger(__name__)

def linebreaksbr(text):
    if not text:
        return text
    import re
    re_newlines = re.compile(r"\r\n|\r")
    value = re_newlines.sub("\n", text)
    return value.replace("\n", "<br>")

def get_schema(context):
    context['tables'] = {}
    context['views'] = {}
    context['schema'] = {}
    for schema_file in settings.SCHEMA_FILES:
        with open(schema_file) as f:
            schema = json.load(f)
            tables = {}
            views = {}
            for n, t in schema.get('tables', {}).items():
                tables[slugify(n)] = t
                lines = []
                for line in t['markdown']:
                    lines.append({k:linebreaksbr(v) for k,v in line.items()})
                t['markdown'] = lines
            schema['tables'] = tables
            context['tables'].update(tables)
            for n, v in schema.get('views', {}).items():
                views[slugify(n)] = v
                lines = []
                for line in v['markdown']:
                    lines.append({k:linebreaksbr(t) for k,t in line.items()})
                v['markdown'] = lines
            schema['views'] = views
            context['views'].update(views)
            context['schema'][schema_file] = schema
            lines = []
            for line in schema['schema']['markdown']:
                if line.startswith('$'):
                    context['schema'][schema_file]['id'] = line.split()
                else:
                    lines.append(linebreaksbr(line))
            schema['schema']['markdown'] = lines

class DatabaseSchemaView(TemplateView):

    template_name = 'queries/schema_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        get_schema(context)
        return context

class TableSchemaView(TemplateView):

    template_name = 'queries/table_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        schema = {}
        get_schema(schema)
        context['schema'] = schema['tables'].get(self.kwargs['table_name'], {})
        return context

class ViewSchemaView(TemplateView):

    template_name = 'queries/table_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        schema = {}
        get_schema(schema)
        context['schema'] = schema['views'].get(self.kwargs['view_name'], {})
        return context

class QueryCreateView(LoginRequiredMixin, CreateView):
    model = ExecuteSQL
    form_class = SQLQueryForm

    def form_valid(self, form):
        if self.request.user.is_authenticated:
            form.instance.user = self.request.user
        result = super().form_valid(form)
        execute.delay(exec_pk=form.instance.pk)
        return result
    
    def get_success_url(self):
        return reverse('queries:query-detail', args=[self.object.pk])

class QueryDetailView(LoginRequiredMixin, DetailView):
    model = ExecuteSQL

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['resulturl'] = reverse("queries:query-result", args=[self.object.pk])
        context['statusurl'] = reverse("queries:query-status", args=[self.object.pk])
        return context

class QueryListView(LoginRequiredMixin, SingleTableMixin, ListView):
    model = ExecuteSQL
    table_class = QueryTable

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)


def get_results(results_file):
    if results_file:
        try:
            table = read_table(results_file)
            if table:
                df = table.to_pandas()
                result = {
                    'columns': table.colnames,
                    'data': df.to_dict(orient='split', index=False)['data'],
                }
                return result
        except Exception as exc:
            logger.error(exc)
            pass
    return {}

class QueryStatusView(LoginRequiredMixin, DetailView):
    model = ExecuteSQL

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        status = {
            'status': self.object.current_status,
            'started': self.object.started,
            'completed': self.object.completed,
            'results_error': linebreaksbr(self.object.results_error),
        }
        return JsonResponse(status)

class QueryResultView(LoginRequiredMixin, DetailView):
    model = ExecuteSQL

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        result = get_results(self.object.results_file)
        return JsonResponse(result)

# Anonymous Queries

class AnonymousQueryCreateView(CreateView):
    model = ExecuteSQL
    form_class = SQLQueryForm

    def form_valid(self, form):
        form.save()
        self.anon = form.instance.anonymousquery_set.create()
        execute.delay(exec_pk=form.instance.pk)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('queries:anonymous-query-detail', args=[self.anon.slug])

class AnonymousQueryDetailView(DetailView):
    model = AnonymousQuery
    template_name = 'queries/executesql_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object'] = self.object.sqlquery
        context['resulturl'] = reverse("queries:anonymous-query-result", args=[self.kwargs['slug']])
        context['statusurl'] = reverse("queries:anonymous-query-status", args=[self.kwargs['slug']])
        return context

class AnonymousQueryStatusView(DetailView):
    model = AnonymousQuery

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        status = {
            'status': self.object.sqlquery.current_status,
            'started': self.object.sqlquery.started,
            'completed': self.object.sqlquery.completed,
            'results_error': linebreaksbr(self.object.sqlquery.results_error),
        }
        return JsonResponse(status)

class AnonymousQueryResultView(DetailView):
    model = AnonymousQuery

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        result = get_results(self.object.sqlquery.results_file)
        return JsonResponse(result)

web/moons/server/queries/templates/queries/executesql_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<div class="container p-4">

    <div class="row">
        <div class="col-3 lead">Query</div>
        <div class="col font-monospace border rounded p-2 m-2">
            {{ object.query | linebreaksbr }}
        </div>
    </div>
    <div class="row my-3">
        <div class="col-3">Status</div>
        <div class="col">
            <div class="h5">
                <span id="job-badge" class="badge text-bg-secondary p-2">
                    <span id="job-spinner" class="d-none spinner-border spinner-border-sm pe-2" aria-hidden="true"></span>
                    <span id="job-status" role="status">{{ object.current_status }}</span>
                </span>
            </div>
        </div>
    </div>
    <div id="div-started" class="row{% if not object.started %} d-none{% endif %}">
        <div class="col-3">Start</div>
        <div id="job-started" class="col">{{ object.started | date:'d/m/Y H:i' }}</div>
    </div>
    <div id="div-completed" class="row{% if not object.completed %} d-none{% endif %}">
        <div class="col-3">End</div>
        <div id="job-completed" class="col">{{ object.completed | date:'d/m/Y H:i' }}</div>
    </div>
    <div id="div-error" class="row{% if not object.results_error %} d-none{% endif %}">
        <div class="col-3">Error</div>
        <div id="job-error" class="col font-monospace border rounded p-2 m-2">{{ object.results_error | linebreaksbr }}</div>
    </div>

    <div>
        <table class="table table-bordered table-striped table-hover table-sm" id="results-table">
            <thead>
                <tr>
                </tr>
            </thead>
        </table>
    </div>
</div>

<link href="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-2.2.1/datatables.min.css" rel="stylesheet">
<script src="https://cdn.datatables.net/v/bs5/jq-3.7.0/dt-2.2.1/datatables.min.js"></script>

<script>

const datetimeFormat = new Intl.DateTimeFormat("en-GB", {dateStyle: "short", timeStyle: "short"})
const fetchStatus = (updateStatus) => {
    return fetch('{{ statusurl }}')
    .then(response => {
        return response.json()
    })
    .then(results => {
        // console.log(results)
        if (results['started']) {
            $('#div-started').removeClass('d-none')
            $('#job-started').text(datetimeFormat.format(new Date(results['started'])))
        }
        if (results['completed']) {
            $('#div-completed').removeClass('d-none')
            $('#job-completed').text(datetimeFormat.format(new Date(results['completed'])))
        }
        if (results['results_error']) {
            console.log('has')
            $('#div-error').removeClass('d-none')
            $('#job-error').html(results['results_error'])
        }
        const status = results['status']
        $('#job-status').text(status)
        $("#job-badge").removeClass();
        if (status == 'Queued') {
            $('#job-spinner').removeClass('d-none')
            $('#job-badge').addClass('badge text-bg-warning p-2')
        }
        else if (status == 'Running') {
            $('#job-spinner').removeClass('d-none')
            $('#job-badge').addClass('badge text-bg-primary p-2')
        }
        else if (status == 'Success' || status == 'Error') {
            $('#job-spinner').addClass('d-none')
            if (status == 'Success') {
                $('#job-badge').addClass('badge text-bg-success p-2')
            }
            if (status == 'Error') {
                $('#job-badge').addClass('badge text-bg-danger p-2')
            }
            clearInterval(updateStatus)
            return true
        }
        return false
    })
    .then((isComplete) => {
        // console.log(`is complete? ${isComplete}`)
        if (isComplete) {
            fetchResults()
        }
        return isComplete
    })
}

const fetchResults = () => {
    fetch('{{ resulturl }}')
    .then(response => {
        return response.json()
    })
    .then(results => {
        if (!('columns' in results)) {
            return
        }
        const columns = []
        for (const col of results['columns']) {
            columns.push({title: col})
        }
        // console.log('construct table')
        let table = new DataTable(
            '#results-table', {
                data: results['data'],
                columns: columns,
                order: [],
                language: {
                    "info": "Showing _START_ to _END_ of _TOTAL_ rows",
                    "lengthMenu": "Show _MENU_ rows",
                }
            }
        );
    })

}
(() => {
    fetchStatus().then((isComplete) => {
        // console.log(`is complete? ${isComplete}`)
        if (!isComplete) {
            const updateStatus = setInterval(function () {
                fetchStatus(updateStatus)
            }, 1000);
        }
    })

    // get results table if ready
})()
</script>

{% endblock %}

web/moons/server/queries/templates/queries/executesql_form.html
{% extends 'core/base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'queries/tree.css' %}">
<style>
/* Split the screen in half */
.split {
  height: 90%;
  position: fixed;
  z-index: 1;
  overflow: scroll;
}

/* Control the left side */
.left {
  left: 0;
  width: 30%;
}

/* Control the right side */
.right {
  right: 0;
  width: 70%;
}
</style>

<style>
    /* Set editor dimensions */
    #editor {
        height: 40vh;
        width: 100%;
    }

    /* Stretch editor to fit inside its containing div */
    .cm-editor {
        height: 100%;
        width: 100%;
    }
</style>

<div class="split left p-4">
    <h5>Database Schema</h5>
    <div>
        <ul class="tree">
        <li>
            <details open>
            <summary>GES</summary>
            <ul>
                <li>
                    <details open>
                        <summary>gesiDR5</summary>
                        <ul id="gesiDR5">
                        </ul>
                    </details>
                </li>
                </ul>
            </details>
            </li>
        </ul>
    </div>
</div>

<div class="split right p-4">

    <div class="">

        <h1>Freeform SQL Query</h1>
    
        <p>This form allows you to submit an SQL query to the MOONS database.</p>
    
    </div>
    
    <div class="">

        <form method="post" enctype="multipart/form-data" id="query-form">

            <div id="div_id_editor" class="mb-3">
                <label for="editor" class="form-label">
                    Query
                </label>
                <div id="editor" class="form-control"></div>
            </div>

            {% crispy form %}

            <input type="submit" class="btn btn-primary" value="Submit" />

        </form>

    </div>


</div>

<script src="{% static 'cm6.bundle.js' %}"></script>

<script>
(() => {
    document.body.addEventListener('dragstart', (e) => {
        const data = e.target.innerText
        e.dataTransfer.setData('text', data);
    });

    const codeSchema = {}
    fetch('{% static "queries/gesiDR5.json" %}')
    .then(response => {
        return response.json()
    })
    .then(schema => {
        const gesiDR5 = document.getElementById('gesiDR5')
        // console.log(schema)
        var listText = ''
        for (let tableName of Object.keys(schema).sort()) {
            let tableData = schema[tableName]
            codeSchema[tableName] = []
            var rowText = `<li><details><summary><span draggable="true">${tableName}</span></summary><ul>`
            for (let col of tableData.data) {
                rowText += `<li><span draggable="true">${col[0]}</span>: <span class="fst-italic">${col[1]}</span></li>`
                codeSchema[tableName].push(col[0])
            }
            rowText += '</ul></details></li>\n'
            listText += rowText
        }
        gesiDR5.innerHTML = listText

        // get current theme (light or dark)
        theme = document.documentElement.getAttribute('data-bs-theme')
        if (theme == 'auto') {
            theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
        }
        let options = (theme == 'dark') ? {oneDark: true} : {}
        // initialise editor
        const initialState = cm6.createEditorState(
            "SELECT ",
            {
                upperCaseKeywords: true,
                schema: codeSchema,
            },
            options,
        );
        const view = cm6.createEditorView(initialState, document.getElementById("editor"));

        document
            .querySelectorAll('[data-bs-theme-value]')
            .forEach(toggle => {
                toggle.addEventListener('click', () => {
                    var theme = toggle.getAttribute('data-bs-theme-value')
                    if (theme == 'auto') {
                        theme = window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
                    }
                    cm6.updateTheme(view, theme === 'dark')
                })
            })

        // on submission set the contents of the query field to the editor document
        var form = document.getElementById("query-form");
        form.addEventListener('submit', () => {
            const editor = document.getElementById("editor")
            const contents = document.querySelector('input[name=query]');
            contents.value = view.state.doc.toString()
        });

     })
})()
</script>
    
{% endblock %}

web/moons/server/queries/templates/queries/executesql_list.html
{% extends 'core/base.html' %}

{% load static %}
{% load render_table from django_tables2 %}

{% block content %}

<div class="container p-4">

    {% render_table table %}

</div>

{% endblock %}

web/moons/server/queries/templates/queries/schema_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<div class="container p-4">

    <h1>Database Schema</h1>
    {% for name, schema in schema.items %}
    <div><a href="#{{ schema.id.1 }}">{{ schema.id.1 }}</a></div>
    {% endfor %}    

    {% for name, schema in schema.items %}
    <div class="card my-4" id="{{ schema.id.1 }}">
        <div class="card-header">
            <h4>{{ schema.id.1 }}</h4>
            <div><small>Latest Revision: {{ schema.id.2 }} {{ schema.id.3 }} {{ schema.id.4 }}</small></div>
        </div>
        <div class="card-body">
            {% for line in schema.schema.markdown %}
            {{ line | safe }}
            {% endfor%}
            {% if schema.tables %}
            <hr>
                <h5>Tables</h5>
                <div>
                    {% for slug, table in schema.tables.items %}
                    <div><a href="{% url 'queries:table-view' slug %}">{{ table.name }}</a></div>
                    {% endfor %}
                </div>
            {% endif %}
            {% if schema.views %}
            <hr>
            <h5>Views</h5>
            <div>
                {% for slug, view in schema.views.items %}
                <div><a href="{% url 'queries:view-view' slug %}">{{ view.name }}</a></div>
                {% endfor %}
            </div>
            {% endif %}

        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

web/moons/server/queries/templates/queries/table_detail.html
{% extends 'core/base.html' %}

{% load static %}

{% block content %}

<div class="container p-4">

    <h1>{{ schema.name }}</h1>
    <div>
        {% for i in schema.markdown %}
        {% for t,l in i.items %}
        {% if t == 'h' %}
        <div class="my-4 lead">{{ l | safe }}</div>
        {% else %}
        {{ l | safe }}
        {% endif %}
        {% endfor %}
        {% endfor %}
    </div>

    {% if schema.statement %}
    <div class="my-4">
        {% for line in schema.statement %}
        <span class="font-monospace">{{ line | linebreaksbr }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if schema.columns %}
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Type</th>
                <th>Length</th>
                <th>Description</th>
                <th>Default Value</th>
                <th>Unified Content Descriptor</th>
            </tr>
        </thead>
        <tbody>
        {% for name, details in schema.columns.items %}
        <tr>
            <td>{{ name }}</td>
            <td>{{ details.type }}</td>
            <td>{{ details.size }}</td>
            <td>{{ details.description | safe }}</td>
            <td>{{ details.default | default:'' }}</td>
            <td>{{ details.unified_content_descriptor }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}

</div>

{% endblock %}