web/moons/server/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
]

web/moons/server/moons/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", include("core.urls")),
    path('queries/', include("queries.urls")),
    path('oidc/', include('mozilla_django_oidc.urls')),
]

web/moons/server/queries/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "queries"

urlpatterns = [
    path('', views.QueryCreateView.as_view(), name='query-create'),
    path('schema', views.DatabaseSchemaView.as_view(), name='schema-view'),
    path('schema/table/<table_name>', views.TableSchemaView.as_view(), name='table-view'),
    path('schema/view/<view_name>', views.ViewSchemaView.as_view(), name='view-view'),
    path('query', views.QueryListView.as_view(), name='query-list'),
    path('query/<int:pk>', views.QueryDetailView.as_view(), name='query-detail'),
    path('query/result/<int:pk>', views.QueryResultView.as_view(), name='query-result'),
    path('query/status/<int:pk>', views.QueryStatusView.as_view(), name='query-status'),
    path('query/an', views.AnonymousQueryCreateView.as_view(), name='anonymous-query-create'),
    path('query/an/<slug>', views.AnonymousQueryDetailView.as_view(), name='anonymous-query-detail'),
    path('query/an/result/<slug>', views.AnonymousQueryResultView.as_view(), name='anonymous-query-result'),
    path('query/an/status/<slug>', views.AnonymousQueryStatusView.as_view(), name='anonymous-query-status'),
]

web/moons/server/core/models.py
from django.db import models

# Create your models here.

web/moons/server/core/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

from django.http import HttpResponse

class IndexView(TemplateView):
    template_name = 'core/index.html'

web/moons/server/core/templates/core/base.html
{% load static %}
{% load django_bootstrap5 %}

<!doctype html>
<html lang="en" data-bs-theme="dark">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MOONS</title>
    <link href="{% static 'bootstrap-5.3.3-dist/css/bootstrap.min.css' %}" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar sticky-top navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">
                <span class="navbar-brand mb-0 h1">MOONS</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'core:index' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Freeform SQL
                </a>
                <ul class="dropdown-menu">
                  {% if user.is_authenticated %}
                  <li><a class="dropdown-item" href="{% url 'queries:query-list' %}">Your Queries</a></li>
                  <li><a class="dropdown-item" href="{% url 'queries:query-create' %}">New Query</a></li>
                  {% else %}
                  <li><a class="dropdown-item" href="{% url 'queries:anonymous-query-create' %}">New Query</a></li>
                  {% endif %}
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Data
                </a>
                <ul class="dropdown-menu">
                  <!-- <li><a class="dropdown-item" href="">Overview</a></li>
                  <li><a class="dropdown-item" href="">Access</a></li>
                  <li><a class="dropdown-item" href="">Releases</a></li> -->
                  <li><a class="dropdown-item" href="{% url 'queries:schema-view' %}">Schema Browser</a></li>
                  <!-- <li><a class="dropdown-item" href="">Known Issues</a></li> -->
                </ul>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Info
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Example Queries</a></li>
                  <li><a class="dropdown-item" href="#">Q&amp;A</a></li>
                  <li><a class="dropdown-item" href="#">Glossary</a></li>
                  <li><a class="dropdown-item" href="#">Publications</a></li>
                  <li><a class="dropdown-item" href="#">Downtime</a></li>
                </ul>
              </li>
            </ul>
            <ul class="navbar-nav">
              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navAuthDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  {{ user.username }}
                </a>
                <div class="dropdown-menu" aria-labelledby="navAuthDropdown">
                  <form action="{% url 'admin:logout' %}" method="post">
                    {% csrf_token %}
                    <input class="dropdown-item" type="submit" value="Logout">
                  </form>
                </div>
              </li>
              {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Login</a></li>
              {% endif %}
                <li class="nav-item dropdown">
                    <button class="btn btn-link nav-link dropdown-toggle" id="bd-theme" type="button" aria-expanded="false" data-bs-toggle="dropdown" data-bs-display="static" aria-label="Toggle theme (auto)">
                        <span class="d-lg-none ms-2" id="bd-theme-text">Toggle theme</span>
                        <svg width="1em" height="1em" class="theme-icon-active">
                          <use href="#icon-auto" />
                        </svg>
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="bd-theme-text">
                        <li>
                            <button type="button" class="dropdown-item" data-bs-theme-value="light" aria-pressed="false">
                              <svg width="1em" height="1em" >
                                <use href="#icon-sun" />
                              </svg>
                              &nbsp; light
                            </button>
                        </li>
                        <li>
                            <button type="button" class="dropdown-item" data-bs-theme-value="dark" aria-pressed="false">
                              <svg width="1em" height="1em">
                                <use href="#icon-moon" />
                              </svg>
                              &nbsp; dark
                            </button>
                        </li>
                        <li>
                            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
                              <svg width="1em" height="1em">
                                <use href="#icon-auto" />
                              </svg>
                              &nbsp; auto
                            </button>
                        </li>
                    </ul>
                </li>
            </ul>
          </div>
        </div>
      </nav>
    <main class="flex-grow-1">
        {% bootstrap_messages %}
        {% block content %}
        {% endblock %}
    </main>
    <!-- SVGs -->
    <svg xmlns="http://www.w3.org/2000/svg" class="base-svgs">
      <symbol id="icon-sun" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8M8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0m0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13m8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5M3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8m10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0m-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0m9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707M4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708"/>
      </symbol>
      <symbol id="icon-moon" fill="currentColor" viewBox="0 0 16 16">
        <path d="M6 .278a.77.77 0 0 1 .08.858 7.2 7.2 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277q.792-.001 1.533-.16a.79.79 0 0 1 .81.316.73.73 0 0 1-.031.893A8.35 8.35 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.75.75 0 0 1 6 .278"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.73 1.73 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.73 1.73 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.73 1.73 0 0 0 1.097-1.097zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.16 1.16 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.16 1.16 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732z"/>
      </symbol>
      <symbol id="icon-auto" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16"/>
      </symbol>
    </svg>

    <!-- END SVGs -->
    <script src="{% static 'bootstrap-5.3.3-dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/switch-theme.js' %}"></script>
  </body>
</html>

web/moons/server/core/templates/core/index.html
{% extends "core/base.html" %}

{% load static %}

{% block content %}
<div class="container flex-grow-1">

    <div class="row m-4">
        <div class="col d-flex flex-column justify-content-between">
            <h1>MOONS Science Archive</h1>
            <p>
                MOONS will be a multi-objects spectrograph mounted at a Nasmyth focus at the VLT. It will have ~1000 fibers deployable over a field of view of ~500 square arcmin. The total wavelength coverage is from 0.6 micron to 1.8 micron, accessed in medium and high resolution modes. In the medium resolution mode (R~4,000-6,000) the entire wavelength range 0.65-1.8 micron is observed simultaneously, while the high resolution mode covers simultaneously two selected spectral regions: one around the CaII triplet (at R~9,000) to measure radial velocities, a second at  R~20,000  in the H-band, for detailed measurements of chemical abundances.
            </p>
        </div>
        <div class="col-sm-3 col-12">
            <img class="img-fluid" src="{% static 'images/MOONS-logo.jpg' %}" alt="MOONS logo">
        </div>
    </div>
    <div class="row m-4">
        <p class="lead">Scientific Objectives</p>
        <p>
            MOONS will be a versatile instrument that will provide ESO and the astronomical community with the observational power necessary to tackle a wide range of Galactic, extragalactic and cosmological studies. Some of the main science cases that are driving the MOONS design are the following:
        </p>
        <dl class="row">
            <dt class="col-sm-3">Galactic archeology.</dt> 
            <dd class="col-sm-9">
                The study of the resolved stellar populations of the Milky Way and other Local Group galaxies can provide us with a fossil record of their chemo-dynamical and star-fomation histories. MOONS will provide a crucial follow-up for the Gaia mission and for Galactic surveys with the VISTA telescope, delivering accurate radial velocities, metallicitites and chemical abundances for several million stars. The near-IR coverage of MOONS will allow to investigate the nature of the heavily-obscured regions of the Galactic bulge.
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-sm-3">The growth of galaxies.</dt>
            <dd class="col-sm-9">
            Tracing the assembly history of galaxies over cosmic time remains a primary goal for observational and theoretical studies of the Universe. Exploiting the large multiplex and wavelength coverage of MOONS will allow for the first time to obtain high quality spectra for a statistically significant number of galaxies (~1 million) at z>1.
            </dd>
        </dl>
        <dl class="row">
            <dt class="col-sm-3">The first galaxies.</dt>
            <dd class="col-sm-9">
            The light from the first galaxies, just a few handred million years after the Big Bang is of great importance to understand the cosmic reionization. The unique combination of the 8m VLT aperture, wide-area coverage, and near-IR spectroscopy offered by MOONS will provide accurate distances, relative veleocities and emission-line diagnositcs for statistical samples of z>7 galaxies.
            </dd>
        </dl>
            Finally, MOONS will provide the essential deep spectroscopic follow-up of current and future optical and near-IR imaging surveys (e.g. VISTA, VST, Pan-STARRS, LSST) and space mission (e.g. WISE, Athena).
            
            </p>
    </div>
    
</div>
{% endblock %}